export class PuzzleEngine {
  constructor(canvas, image, size) { this.canvas = canvas; this.ctx = canvas.getContext('2d'); this.image = image; this.size = size; this.pieces = []; this.moves = 0; this.mistakes = 0; this.selected = null; this.build(); }
  build() { const total = this.size * this.size; this.pieces = Array.from({ length: total }, (_, index) => ({ correct: index, position: index, rotation: 0 })); for (let index = total - 1; index > 0; index--) { const swap = Math.floor(Math.random() * (index + 1)); [this.pieces[index].position, this.pieces[swap].position] = [this.pieces[swap].position, this.pieces[index].position]; } this.draw(); }
  cellAt(x, y) { const cell = this.canvas.width / this.size; const col = Math.floor(x / cell); const row = Math.floor(y / cell); return row >= 0 && row < this.size && col >= 0 && col < this.size ? row * this.size + col : -1; }
  select(x, y) { const position = this.cellAt(x, y); this.selected = this.pieces.find((piece) => piece.position === position) || null; return this.selected; }
  dragSelected(x, y) { if (!this.selected) return; this.selected.dragX = x; this.selected.dragY = y; this.draw(); }
  releaseSelected(x, y) { if (!this.selected) return; const target = this.cellAt(x, y); const other = this.pieces.find((piece) => piece.position === target); if (target >= 0 && other && other !== this.selected) { [this.selected.position, other.position] = [other.position, this.selected.position]; this.moves++; this.mistakes += this.selected.position !== this.selected.correct ? 1 : 0; } delete this.selected.dragX; delete this.selected.dragY; this.selected = null; this.draw(); }
  rotateSelected() { if (this.selected) { this.selected.rotation = (this.selected.rotation + 90) % 360; this.moves++; this.draw(); } }
  solved() { return this.pieces.every((piece) => piece.position === piece.correct && piece.rotation === 0); }
  draw() { const cell = this.canvas.width / this.size; this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height); for (const piece of this.pieces) { const sourceRow = Math.floor(piece.correct / this.size); const sourceCol = piece.correct % this.size; const row = Math.floor(piece.position / this.size); const col = piece.position % this.size; const centerX = piece.dragX ?? col * cell + cell / 2; const centerY = piece.dragY ?? row * cell + cell / 2; this.ctx.save(); this.ctx.translate(centerX, centerY); this.ctx.rotate(piece.rotation * Math.PI / 180); this.ctx.drawImage(this.image, sourceCol * this.image.width / this.size, sourceRow * this.image.height / this.size, this.image.width / this.size, this.image.height / this.size, -cell / 2, -cell / 2, cell, cell); this.ctx.restore(); if (piece === this.selected) { this.ctx.strokeStyle = '#e85d83'; this.ctx.lineWidth = 5; this.ctx.strokeRect(centerX - cell / 2 + 3, centerY - cell / 2 + 3, cell - 6, cell - 6); } } }
}
